// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  readonly 'hyphened-classname': string;
  readonly 'otherClass': string;
  readonly 'someClass': string;
  readonly 'underscored_classname': string;
  readonly 'validClass': string;
}
export const cssExports: CssExports;
export default cssExports;
