// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  [key: string]: void;
  'hyphened-classname': string;
  'otherClass': string;
  'someClass': string;
  'underscored_classname': string;
  'validClass': string;
}
declare const cssExports: CssExports;
export = cssExports;
