// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classInBothFiles': string;
  'classInTypeScriptFile': string;
}
export const cssExports: CssExports;
export default cssExports;
